Restrict donations in USD, GBP and EUR to 10
MozillaFoundation/donate-wagtail pull request #1699
Opened 2022-09-15 10:45 UTC by tomusher

Can be rolled back when other fraud mitigation methods are implemented. 

Affects monthly donations as the same logic is used to determine minimum so the available preset donations has also been changed.

Messaging updated to describe the reasoning behind the minimum.

2022-09-15 11:41 UTC, TheoChevalier requested changes
Just a small typo to fix

2022-09-15 11:41 UTC, TheoChevalier commented on donate/templates/fragments/donate_form.html
> +                            {% blocktrans with min_amount=minimum_amount trimmed %}To combat fraud, Mozilla Foundation has temporarily restricted donations to a mininum of {{ min_amount }}{% endblock
```suggestion
                            {% blocktrans with min_amount=minimum_amount trimmed %}To combat fraud, Mozilla Foundation has temporarily restricted donations to a minimum of {{ min_amount }}{% endblocktrans %}
```

2022-09-15 11:50 UTC, tomusher commented on donate/templates/fragments/donate_form.html
> +                            {% blocktrans with min_amount=minimum_amount trimmed %}To combat fraud, Mozilla Foundation has temporarily restricted donations to a mininum of {{ min_amount }}{% endblock
Good catch thank you, fixed!

2022-09-15 23:21 UTC, danielfmiranda approved these changes
Hi Tom! Thanks for the tag, this looks good to me, approved! 👍

2022-09-16 09:04 UTC, TheoChevalier approved these changes

2022-09-21 14:38 UTC, merged